### ISSUE TITLE
Definir src/main/resources/application.properties ou application.yaml do projeto

### ISSUE THREAD

**Issue by AndreWakugawa** [DevXMinds/Pipeline-DomRock#20]
Apoio:
https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
https://www.geeksforgeeks.org/spring-boot-application-properties/
https://www.baeldung.com/spring-boot-yaml-vs-properties
https://stackoverflow.com/questions/61835683/spring-yaml-and-properties-configurations

##DoD
- Configurar DataSource com PostgreSQL
- Configurar o hibernate.ddl-auto
- Configurar Multipart File (spring.servlet.multipart.max-file-size e spring.servlet.multipart.max-request-size)

**Comment by Caio-sousaFatec** [comment]
Realizado no commit: 3357616a
