### ISSUE TITLE
Definir a Entity "Files" ou "Arquivo"

### ISSUE THREAD

**Issue by AndreWakugawa** [DevXMinds/Pipeline-DomRock#21]
Apoio:
https://medium.com/@bubu.tripathy/best-practices-entity-class-design-with-jpa-and-spring-boot-6f703339ab3d
https://spring.io/guides/gs/accessing-data-jpa
https://www.baeldung.com/jpa-entities

Apoio para Geradores de ID:
https://stackoverflow.com/questions/72333141/how-to-automatically-generate-id-in-sequence-in-spring-jpa
https://stackoverflow.com/questions/2595124/how-does-the-jpa-sequencegenerator-annotation-work

!!! Lembrar de definir 

~~~
@Table (name = "[nome da tabela no PostgreSQL]")
~~~

##DoD
- Entidade com atributos, construtores, getters e setters
- Atributos:

~~~
	@Id
        @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "fileID")
        @SequenceGenerator(name = "fileID", allocationSize=1)
	private String id;

	private String name;

	private String type;

	@Lob
	private byte[] data;
~~~

**Comment by GabrielBartolomeu1** [comment]
Closed com o commit 016aa0a
