### ISSUE TITLE
REST: Criação de Controller da Entity File

### ISSUE THREAD

**Issue by AndreWakugawa** [DevXMinds/Pipeline-DomRock#25]
Apoio:
https://github.com/OusamaELIDRISSI/upload-files-database/blob/main/src/main/java/ma/files/store/controller/FileController.java

https://www.bibliaon.com/

Boa sorte!

## DoD
- Upload funcional da Entity #21 com Post
- Get funcional de todos os Files na DB
- Uso do service #24

**Comment by CauevSilv** [comment]
Closed on 5655829e6215964600ef08b178cde8c559ec85ff

07/04/2024
