### ISSUE TITLE
POST user: criação de conta

### ISSUE THREAD

**Issue by AndreWakugawa** [DevXMinds/Pipeline-DomRock#53]
## DoD
- enviar nome_user
- enviar email
- enviar senha
- enviar nivel de acesso
- enviar id_empresa (da empresa)
- enviar setor (da empresa)

PORFA FAZER DDL DE TABELA DE NIVEL DE ACESSO
FAZER TABELAS DE NIVEL DE ACESSO POR USUARIO (M:M)

**Comment by CauevSilv** [comment]
Feito no commit 7271ddd
